### ISSUE TITLE
job types should have a project relationship

### ISSUE THREAD

**Issue by opalmer** [pyfarm/pyfarm-master#47]
_Issue by **[opalmer](https://github.com/opalmer)** from Wednesday Dec 18, 2013 at 05:18 GMT_
_Originally opened as https://github.com/pyfarm/pyfarm-models/issues/27_

----

Projects may need to override a job type definition however the current job type model does not support this.  Add a project relationship so that a job type can be associated with 0+ specific projects.

**Comment by guidow** [comment]
We do not have a projects table any more.
