### ISSUE TITLE
Use fixpoint datatype for frames instead of float

### ISSUE THREAD

**Issue by opalmer** [pyfarm/pyfarm-master#49]
_Issue by **[guidow](https://github.com/guidow)** from Wednesday Jan 15, 2014 at 15:21 GMT_
_Originally opened as https://github.com/pyfarm/pyfarm-models/issues/33_

----

The database tables in pyfarm-models are currently using float datatypes to reference frame numbers. This seems suboptimal to me. We are not going to use the large data range offered by floats anyway, but we might need to compare two frame/subframe numbers for equality. We may also need to rely on frame 1.0 plus a step value of 0.1 giving exactly subframe 1.1, and not, for example, 1.999999 or 1.100001, which is not a given when using floats.

I think we should be using fixed point numbers, like for example DECIMAL(10, 4), instead for those.

**Comment by guidow** [comment]
This has been solved a long time ago.
